apiVersion: v1
kind: Service
metadata:
  name: postgres-ha-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: db.lab.techyon.dev
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: PostgreSQL
    gethomepage.dev/description: CloudNative PG HA Cluster
    gethomepage.dev/group: Databases
    gethomepage.dev/icon: postgres.png
spec:
  type: LoadBalancer
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    cnpg.io/cluster: postgres-ha
    role: primary
