apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-role-admin
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore
  target:
    name: pg-role-admin
    creationPolicy: Owner
    template:
      data:
        username: admin
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: PostgresHAAdmin
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-role-paperclip
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore
  target:
    name: pg-role-paperclip
    creationPolicy: Owner
    template:
      data:
        username: paperclip
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: PostgresHA
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-role-necronia
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore
  target:
    name: pg-role-necronia
    creationPolicy: Owner
    template:
      data:
        username: necronia
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: PostgresHA
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-role-techyon
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore
  target:
    name: pg-role-techyon
    creationPolicy: Owner
    template:
      data:
        username: techyon
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: PostgresHA
        property: password
