apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-role-paperclip
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore
  target:
    name: pg-role-paperclip
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: PostgresHA
        property: paperclipPassword
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-role-necronia
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore
  target:
    name: pg-role-necronia
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: PostgresHA
        property: necroniaPassword
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-role-techyon
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore
  target:
    name: pg-role-techyon
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: PostgresHA
        property: techyonPassword
