apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-ha
spec:
  instances: 3

  storage:
    size: 8Gi
    storageClass: qnap-iscsi

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"

  monitoring:
    enablePodMonitor: true

  managed:
    roles:
      - name: admin
        ensure: present
        login: true
        superuser: true
        createdb: true
        createrole: true
        passwordSecret:
          name: pg-role-admin
      - name: paperclip
        ensure: present
        login: true
        superuser: false
        createdb: false
        passwordSecret:
          name: pg-role-paperclip
      - name: necronia
        ensure: present
        login: true
        superuser: false
        createdb: false
        passwordSecret:
          name: pg-role-necronia
      - name: techyon
        ensure: present
        login: true
        superuser: false
        createdb: false
        passwordSecret:
          name: pg-role-techyon

  bootstrap:
    initdb:
      postInitSQL:
        - CREATE DATABASE paperclip;
        - CREATE DATABASE necronia;
        - CREATE DATABASE techyon;
