image:
  repository: ghcr.io/t3chy0n/paperclip
  tag: "latest"

imagePullSecrets:
  - name: ghcr-docker

betterAuthSecret: "7fcc4bc0c4080324badf8297b692bf8d035203273275c3fa03ff800d8fcc7756"

persistence:
  enabled: true
  size: 5Gi
  storageClass: qnap-iscsi
