apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperclip-db-credentials
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore

  target:
    name: paperclip-db-credentials
    creationPolicy: Owner
    template:
      data:
        uri: "postgres://paperclip:{{ .pgPassword }}@postgres-ha-rw.databases.svc.cluster.local:5432/paperclip"

  data:
    - secretKey: pgPassword
      remoteRef:
        key: PostgresHA
        property: password
