apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperclip-secrets
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore

  target:
    name: paperclip-secrets
    creationPolicy: Owner

  data:
#    - secretKey: anthropicApiKey
#      remoteRef:
#        key: AnthrtopicClaude
#        property: password

    - secretKey: openaiApiKey
      remoteRef:
        key: OpenAI
        property: password
