apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-docker
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore

  target:
    name: ghcr-docker
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"t3chy0n","password":"{{ .ghcrToken }}"}}}

  data:
    - secretKey: ghcrToken
      remoteRef:
        key: GHCR
        property: password
